### ISSUE TITLE
What about polyfills?

### ISSUE THREAD

**Issue by odahcam** [coliff/bootstrap-ie8#3]
- https://github.com/afarkas/html5shiv
- https://github.com/jonathantneal/flexibility
- https://github.com/FremyCompany/css-grid-polyfill
- https://github.com/etianen/html5media
- http://www.createjs.com/soundjs
----
See more in https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills.

**Comment by coliff** [comment]
Hi there.
- **html5shiv** - We already recommend using this for IE 8 and below (see the conditional statement snippet on this projects README
- **Flexibility** is (sadly) no longer actively maintained and the latest version is completely broken and doesn't work at all. I am on the lookout for a Flexbox polyfill for IE8/IE9 but I can't seem to find one that works
- **CSS-Grid-Polyfill** - Not needed as Bootstrap 4 doesn't use CSS Grid
- **HTML5Media** - Not needed for this project
- **SoundJS** - Not needed for this project

**Comment by odahcam** [comment]
Flexibility was recently updated. Have you take a look?

**Comment by coliff** [comment]
It shows that it was last updated on 30 Jun 2016. The 2.0.1 version doesn't work - if you look at the issues there there are many people reporting that...

**Comment by odahcam** [comment]
Oh, my bad, I mistaken tought that flexibility was update in 30 Jun 2017. Maybe dropping support and showing a floted grid is a good thing at all. I also sent this repo to some people in the BS's Slack team.
