### ISSUE TITLE
Add CSS workaround for Flexbox

### ISSUE THREAD

**Issue by coliff** [coliff/bootstrap-ie8#5]
There are no working JavaScript polyfills available for Flexbox for us to use so we'll need to provide a workaround CSS-based solution, likely being a fallback to the grid system used in Bootstrap 3.

**Comment by TeamUpDevelopment** [comment]
This is hacky AF, but it works for my IE9 compatibility needs which are to make it usable, but not an exact experience as a modern browser... basically, just float everything that is using flexbox model and do some old school hacks to clear it all....



`.card-group .card,
.col-1, .col-2, .col-3, .col-4, .col-5, .col-6, .col-7, .col-8, .col-9, .col-10, .col-11, .col-12, .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12, .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12, .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12, .col-xl-1, .col-xl-2, .col-xl-3, .col-xl-4, .col-xl-5, .col-xl-6, .col-xl-7, .col-xl-8, .col-xl-9, .col-xl-10, .col-xl-11, .col-xl-12 {
    float: left;
}
.row, .container-fluid, .container, section, footer, main, aside {
    clear: both;
    display:block;
    width:100%;
    height: 100%;
    overflow:hidden;
}`

**Comment by Tahiche** [comment]
@TeamUpDevelopment Your solution works.
I was expecting the row, col and other grid elements to be included in the css file. This are the crucial elements when trying to (partially) support IE<10. 
Shouldn´t this be included in "css/bootstrap-ie8.css" ?.

**Comment by TeamUpDevelopment** [comment]
.row is included in the example above along with the other grid elements. I think the only target that is not in there is .col which would be added to the ruleset targeting the columns.

**Comment by coliff** [comment]
Thanks for the CSS @TeamUpDevelopment  - I've added it to the foot of the CSS for now.
PRs are most welcome if you can improve it further!

**Comment by TeamUpDevelopment** [comment]
I think the challenge with it though is 'guessing' the width for the '.col' class when dealing with IE < 10
.col probably would not bode well those browsers because older IE will expect a width value for the float box model.

**Comment by coliff** [comment]
I reworked the CSS and its much improved now;

- The bootstrap-ie9.css provides just the float-based fallback. In my testing it works well
- The bootstrap-ie8.css provides fixes for the many features which IE8 doesn't support (media queries, opacity, rem units and more). This CSS also sets the container width to a set-width and is not responsive which means the RespondJS polyfill is no longer needed - this has many advantages, faster to render and allows this CSS to be hosted on a CDN.

**Comment by heyrm** [comment]
Any update on the '.col' elements and is there any reason why can't fix this with JS? 

it's easy to calculate the sizes the '.col' elements need to be... or is there some other reason why you don't want to fix this in JS as I think it's the only way.

**Comment by coliff** [comment]
Hi @heyrm - there will be a JavaScript included in this project in the next release, it's dependent on a fix to Bootstrap core JS which is included in the forthcoming 4.1.1 release. It fixes the dropdown menus and modals so far.

I'm not so sure if fixing the cols with JS on IE8/IE9 is a good idea though, it could be expensive to calculate and could delay rendering the page and would mean JS would need to go in the header. If you want to have a go at working on a solution anyway, feel free to post a link if you get it working well.
