### ISSUE TITLE
Navbar not working

### ISSUE THREAD

**Issue by Tahiche** [coliff/bootstrap-ie8#6]
Hi, 
Navbars are hidden (collapsed) in IE9. Suppose it´s got to do with JS.
![image](https://user-images.githubusercontent.com/491834/30312432-cb269e6e-9799-11e7-9fdc-8c42779bfe0f.png)

**Comment by namiltd** [comment]
Check: http://namiltd.github.io/bootstrap-ie8/navbar.htm

**Comment by coliff** [comment]
This issue is fixed now with the latest release - thanks to @namiltd for the PR!
