### ISSUE TITLE
NPM install issue with browserslist

### ISSUE THREAD

**Issue by LinusBF** [coliff/bootstrap-ie8#67]
Hi

I just installed this package with NPM and got the following error when compiling:
` error  in ./node_modules/bootstrap-ie8/css/bootstrap-ie8.css`
`Module build failed: BrowserslistError: .\node_modules\bootstrap-ie8 contains both .browserslistrc and package.json with browsers`

I resolved the issue locally by deleting the `.browserslistrc` file. I'm guessing one could remove the `browsers` value in `package.json` just as well.
I don't know if both of these are needed outside of NPM installs, but it would be nice to not have to do delete the files manually when I run `npm install` in the future. Or maybe there is something I'm missing that would resolve this?

Right now I'm just including the package by having `require('bootstrap-ie8')` in my entry JS file. (I'm using VueJS)
Maybe this is the wrong way to include the package?

In any case, thank you for spending your time creating this package! :)

**Comment by coliff** [comment]
Hi @LinusBF - thanks for reporting this issue. You're right - projects should only really include the browserlist in the `package.json` or in the `.browserslistrc` - but not both. I'll delete the `.browserslistrc` file now. Thanks!

**Comment by coliff** [comment]
Fixed in #68
I won't release an update on NPM yet though. I'll wait for Bootstrap 4.2.0 as there'll be a few additions to the CSS then.

**Comment by LinusBF** [comment]
Cool, thanks for the quick response!
