### ISSUE TITLE
Your project in composer

### ISSUE THREAD

**Issue by EifX** [coliff/bootstrap-ie8#70]
Hey,

can you add your project in composer? I have made an example-file for you :)

`{
	"name": "coliff/bootstrap-ie8",
	"description": "Bootstrap 4 for IE8 and IE9",
	"version": "4.1.3",
	"licence": "MIT",
	"authors": [
		{
			"name": "Christian Oliff",
			"email": "christianoliff@yahoo.com",
			"homepage": "https://christianoliff.com",
			"role": "Developer"
		}
	],
	"support": {
		"issues" : "https://github.com/coliff/bootstrap-ie8/issues",
		"docs" : "https://github.com/coliff/bootstrap-ie8#readme"
	}
	"require": {
	  	"twbs/bootstrap": "4.1.3"
	}
}
`

**Comment by coliff** [comment]
Hi - I haven't used Composer before... are you suggesting I simply add a 'composer.json' to the root of the project? If so, I can do that today,

**Comment by EifX** [comment]
Hey, yes, this is the first step. After this, you can create an account on https://packagist.org/register/ and publish your project on this plattform. Then your project appears in packagist.org and can downloaded with composer.

It's nice for little PHP-Projects to have it in composer, because I need only one package-manager. Thank you for your support :)

**Comment by coliff** [comment]
sounds good - I'll add it. :-)

The JSON is showing an error for me in VS Code:
```
{
  "name": "coliff/bootstrap-ie8",
  "description": "Bootstrap 4 for IE8 and IE9",
  "version": "4.1.3",
  "licence": "MIT",
  "authors": [
    {
      "name": "Christian Oliff",
      "email": "christianoliff@yahoo.com",
      "homepage": "https://christianoliff.com",
      "role": "Developer"
    }
  ],
  "support": {
    "issues": "https://github.com/coliff/bootstrap-ie8/issues",
    "docs": "https://github.com/coliff/bootstrap-ie8#readme"
  } 
  "require": {
    "twbs/bootstrap": "4.1.3"
  }
}
```

Shouldn't there be a comma after the support { } ?

**Comment by EifX** [comment]
Yes ;) Sorry, my mistake. Thank you very much!

**Comment by coliff** [comment]
cool - thanks for the suggestion. Added it now:
https://packagist.org/packages/coliff/bootstrap-ie8
