### ISSUE TITLE
Demo no longer working (Windows 7 - IE8)

### ISSUE THREAD

**Issue by fareskalaboud** [coliff/bootstrap-ie8#74]
The library isn't working, for some reason.

I'm testing the demo page (using the [Windows 7 VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) to test on IE8) and I'm getting the result below:

![image](https://user-images.githubusercontent.com/4170046/48677462-4a945d80-eb6d-11e8-89e8-8965cda06f3d.png)

Developer tools giving me this:
![image](https://user-images.githubusercontent.com/4170046/48677472-6861c280-eb6d-11e8-8084-7ebdde83f31e.png)

**Comment by coliff** [comment]
The demo is working for me.. and I just retested with:
https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/?url=http%3A%2F%2Fcoliff.github.io%2Fbootstrap-ie8%2Ftest.htm
and it shows as working there too. Can you try again?

**Comment by coliff** [comment]
It's confirmed working with Windows 7 on VirtualBox too so I'll close this issue. Let me know if you still have issues.
