### ISSUE TITLE
modernizr should i use or not

### ISSUE THREAD

**Issue by peeyush79** [coliff/bootstrap-ie8#82]
also should i use this tags or not

**Comment by coliff** [comment]
I personally don't use Modernizr and haven't felt the need to use it. You don't need to use with this project.

I'm a big fan of the Polyfill.io service though - Just add `<!--[if IE]><script src="https://cdn.polyfill.io/v3/polyfill.min.js"></script><![endif]-->` and it'll automatically fix lots of things in IE9 and lower.
