### ISSUE TITLE
work on the rtl versions ?

### ISSUE THREAD

**Issue by djary** [coliff/bootstrap-ie8#89]
Hi rtl versions are separate files (bootstrap-rtl.css / bootstrap-rtl.js) . but it seems bootstrap-ie8 support english version only ex: https://cdn.jsdelivr.net/gh/coliff/bootstrap-ie8/css/bootstrap-ie9.min.css

**Comment by coliff** [comment]
Hi - which Bootstrap RTL files are you referring to? If you need customisation I'd suggest downloading the CSS and self-hosting with the modifications you need.
