### ISSUE TITLE
Create bootstrap-ie10

### ISSUE THREAD

**Issue by techboyg5** [coliff/bootstrap-ie8#91]
The Bootstrap 5 alpha is coming soon. How about create some patches to support Bootstrap 5 on IE 10 and IE 11?

**Comment by techboyg5** [comment]
The first Bootstrap 5 alpha has been released.

**Comment by coliff** [comment]
Bootstrap-ie11 is available for Bootstrap 5 now!
https://github.com/coliff/bootstrap-ie11
